//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace collegefeedbacksystem24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string FeedbackType { get; set; }
        public string FeedbackText { get; set; }
    }
}
