//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace collegefeedbacksystem24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userregistration
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string uemail { get; set; }
        public string upass { get; set; }
        public string cpass { get; set; }
        public string crole { get; set; }
    }
}
